### PR TITLE
Add an underscore string extension method

### PR DESCRIPTION
**Pull request by robi-y**
Please note again that  I've added a suppress for CLS compliance!
Spec included too

### CODE REVIEW

**Comment by adamralph** [comment]
Linking to https://github.com/xbehave/xbehave.net/issues/72

**Comment by adamralph** [comment]
Thanks very much @robi-y

**Comment by adamralph** [comment]
@robi-y this change is included in the latest beta https://nuget.org/packages/Xbehave/0.15.0-beta04

**Comment by robi-y** [comment]
Thanks

**Pull request merged**
