### PR TITLE
#63 cherry picked contributions and added null check

### LINKED ISSUE #63: Add f() extension method
Suggested and contributed by @glennblock

Was originally X(), changed to f() in https://github.com/xbehave/xbehave.net/issues/67

### PR DESCRIPTION
**Pull request by adamralph**
fixes #63

### CODE REVIEW

**Comment by glennblock** [comment]
@adamralph I am noticing an issue with this style. It looks like when I run the tests now in the runner, I don't get the GWT for a particular test in sequence. I see multiple Givens, multiple Whens etc and can't correlate. 

I don't think that was happening before. Is that a product of [Example?]

**Comment by glennblock** [comment]
@adamralph I just tested. Night and day difference with the old style. All the tests show in sequence very clearly NOT using [Example]

**Comment by glennblock** [comment]
This is how it looks if I use the old style

bdd

**Comment by glennblock** [comment]
And this is using the new style which is mixed up.
bdd2

**Comment by glennblock** [comment]
I guess looking at above what I said before is not true, they do correlate but they are out of order in terms the way they were defined in the [Example] attrributes wheras in the first example it is in the exact order.

**Comment by adamralph** [comment]
Yeah, unfortunately there's no way around that (AFAIK).

xBehave preserves the order that it sees using `System.Reflection` and I believe xUnit preserves the order it gets from xBehave but somewhere in the pipeline of csc.exe, JIT compiler and `System.Reflection` the order gets mangled. I don't know who the culprit is.

That said, the order of the examples is usually not important and nothing should ever have a hard dependency on it. I find this causes me no problems in practice.

**Comment by robi-y** [comment]
Maybe something like the TestPriority of xunit samples could help
http://xunit.codeplex.com/SourceControl/latest#samples/PrioritizedFixtureExample/Examples.cs

**Comment by glennblock** [comment]
Maybe order doesn't matter.

**Comment by adamralph** [comment]
Apart from aesthetics, the order of example execution doesn't matter. Obviously steps within a scenario need to be run in order and that is guaranteed (nothing to do with reflection there).

@robi-y `[TestPriority]` looks interesting but it seems to be scoped only to a test method definition, rather than each test in the multiple tests which are yielded from a data driven test.

**Pull request merged**
