### PR TITLE
#25 refactor: change Step to have just abstract Execute()

### PR DESCRIPTION
**Pull request by adamralph**
ref #25

### CODE REVIEW

**Comment by adamralph** [comment]
@dschenkelman this is the PR I was talking about. There are a few things going on here:
- I've moved `AsyncTestSyncContext` to a private nested class in `SyncStep` since that's the only place it's needed
- `Step` is now really simple and just contains an `abstract Execute()`
- `AsyncStep` is really simple and is in fact pretty much just lifted out of your initial commit, before the dicussions about inheritance and `async void`
- `SyncStep` is now the only complicated step class due to the support for `async void` and timeouts

**Comment by dschenkelman** [comment]
@adamralph I really like the change. When you had asked me to simplify the inheritance hierarchy I understood that you wanted to make sure both approaches had as much code in common as possible. I'm glad the old `AsyncStep` is back, as the new approach required jumping through hoops to get them both working together :-)

**Comment by adamralph** [comment]
@dschenkelman great, thanks for taking a look. I realised there was one scenario not satisifed, i.e. when an async step fails but within the timeout. That's fixed by the last commit.

**Comment by dschenkelman** [comment]
@adamralph great! looking forward to using this. Is there a release date?

**Comment by adamralph** [comment]
Not yet, we'll have to fix the disposable object registrations for async tasks first.

**Pull request merged**
