### PR TITLE
Initial proposal to fix #25.

### LINKED ISSUE #25: Support async steps
To allow async step definition, e.g.

``` C#
"Given foo"
    f.(async () => await Foo());
```

### PR DESCRIPTION
**Pull request by dschenkelman**
Feedback is welcome.

### CODE REVIEW

**Comment by adamralph** [comment]
Just an initial observation - the build is failing due to StyleCop violations. It should be very quick to go through these and fix them. When you build in VS in Debug the violations will show as warnings in the Error List. When you build in Release they will show as errors and the build will fail.

Before pushing, a successful local `rake` should ensure that the CI build will also succeed.

**Comment by adamralph** [comment]
Thanks for fixing the StyleCop violations.

The build is still failing but codebetter CI is down :cry: (usual at the weekends). I pulled the code down and ran `rake` and got failed tests. Do you get the same?

**Comment by dschenkelman** [comment]
That is weird. I'm having issues getting e-mail comments displayed (I had left two):

I have pushed the updates with the SA fixes.

Something weird is happening in my machine. Unit tests work perfectly fine in VS, but I'm getting an error when running with rake. Would you mind checking if the same things happens in your machine?

Just to get a better idea of how to fix it.

The full stack I'm getting with rake is here:

```
Tests complete: 42 of 19System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invoc
ation. ---> System.InvalidOperationException: oops
   at Xbehave.Test.Acceptance.ScenarioFeature.FeatureWithAFailingStepBeforeContinueOnFailureStepType.<Scenario>b__5f() i
n c:\Users\Damian\Documents\GitHub\xbehave.net\src\test\Xbehave.Features.Net40\ScenarioFeature.cs:line 296
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttrib
utes methodAttributes, RuntimeTypeHandle typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters
, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters
, CultureInfo culture)
   at Xbehave.Sdk.SyncStep.<>c__DisplayClass1.<Execute>b__0(Object o) in c:\Users\Damian\Documents\GitHub\xbehave.net\sr
c\Xbehave.Sdk.Net40\SyncStep.cs:line 36
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallbackInternal(_ThreadPoolWaitCallback tpWaitCallBack)
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback(Object state)
```

**Comment by adamralph** [comment]
Yeah, I get exactly the same error. I can only imagine it's something to do with the threading behaving differently in the GUI context (VS) and the console context (xunit.console.exe). I haven't had time to dig into the code properly yet though.

**Comment by dschenkelman** [comment]
@adamralph I'll try to figure it out. It might not be today, but I will start working on it.

**Comment by adamralph** [comment]
@dschenkelman I've taken a look at the `Step`, `SyncStep` and `AsyncStep` inheritance graph and it hasn't quite worked out how I envisaged. I thought that we could do almost all the work in the base class with `SyncStep` and `AsyncStep` both being tiny and just closing the type parameter to `Action` and `Func<Task>` respectively, providing a constructor and overriding something like `protected abstract Task GetTask();`.

When I suggested this inheritance I was unaware of the intricacies required to do the task execution with regard to the synch context etc. and in retrospect, given what you've discovered, perhaps it wasn't the best idea. I think the fact that we have `Step.ExecuteMethodInfo()` returning `object` and you're having to do `var bodyTask = (Task)this.ExecuteMethodInfo();` in `AsyncStep` suggests that something is wrong in the model. Do you think it would be easier to drop the inheritance?

**Comment by dschenkelman** [comment]
@adamralph I'll spend some time figuring out how to improve the `Step` hierarchy. I did try a couple of different things originally, but the fact that `Func<Task>` and `Action` are radically different and having to support timeouts kind of gets in the way of cleaner code. Nevertheless, now that a couple of days have gone by I'll give it another look to see if I can come up with a better approach.

The one thing I like about this one is that it kept the `AsyncStep` class mostly clean and simple to read. `SyncStep` is a different animal since we need to handle `async void` +  timeouts so the logic gets a bit more complicated.

**Comment by adamralph** [comment]
ref #25

**Comment by adamralph** [comment]
@dschenkelman thank you, it's awesome to finally be able to merge this PR. Thanks for all your considerable effort on it.

Incidentally, there is a bug in the current 1.0 release which I wasn't aware of until I reviewed your changes. If a step registers disposable objects with `.Using()` and the step has a timeout, because we do a `BeginInvoke()` on the action which obviously goes off on it's own thread, those object registrations are lost. However, in your `SyncStep` changes you've fixed this by adding the code that pulls the teardowns from the worker thread and re-adds them in the main thread.

However, there's still a problem with async steps. Since they run on their own thread within the `Task`, the object registrations are getting lost. I have some ideas about how to get around this which I'll play around with.

I did a few refactorings whilst I reviewed your changes which I'll merge in separately, probably in 2 PR's. The first is trivial but the second one I'd like to get your opinion on if you don't mind spending some time reviewing it.

**Comment by dschenkelman** [comment]
@adamralph Sure, just let me know. I'll be glad to do it.

What are you referring to when you mention about "object registrations"?

**Comment by adamralph** [comment]
It's this feature https://github.com/xbehave/xbehave.net/wiki/Object-disposal

It uses a thread static collection to collect the disposable objects which are registered within a step body with the `Using()` extension method. Since async step run on their own thread, after the step has completed there's no way for the `AsyncStep` thread to get a handle on those objects.

**Pull request merged**
